const fs=require('fs'),path=require('path'),vm=require('vm'),os=require('os');
const TPS=254016000000,tmp=fs.mkdtempSync(path.join(os.tmpdir(),'hexa-v31-animated-host-'));
function coll(a,prop){Object.defineProperty(a,prop||'numItems',{get(){return a.length;},configurable:true});return a;}
class Time{constructor(){this.seconds=0;}get ticks(){return String(Math.round(this.seconds*TPS));}} global.Time=Time;
class XFile{constructor(p){this.path=String(p);this.encoding='UTF-8';this._mode='';this._buf='';}get exists(){return fs.existsSync(this.path);}get fsName(){return path.resolve(this.path);}get name(){return path.basename(this.path);}get length(){try{return fs.statSync(this.path).size;}catch(_e){return 0;}}get parent(){const self=this;return{get exists(){return fs.existsSync(path.dirname(self.path));},get fsName(){return path.dirname(self.path);},create(){fs.mkdirSync(path.dirname(self.path),{recursive:true});return true;}};}open(m){this._mode=m;if(m==='r')this._buf=fs.readFileSync(this.path,'utf8');else this._buf='';return true;}read(){return this._buf;}write(s){this._buf+=String(s);if(this._mode==='w'){fs.mkdirSync(path.dirname(this.path),{recursive:true});fs.writeFileSync(this.path,this._buf,'utf8');}return true;}close(){return true;}remove(){try{if(this.exists)fs.unlinkSync(this.path);return true;}catch(_e){return false;}}} global.File=XFile;
class PItem{constructor(p,isBin=false){this._p=p||'';this.children=coll([]);this._bin=isBin;this.name=isBin?path.basename(p||'bin'):path.basename(p||'media');}getMediaPath(){return this._bin?'':this._p;}createBin(n){const b=new PItem(n,true);this.children.push(b);return b;}}
class Clip{constructor(track,pi,start){this._track=track;this.projectItem=pi;this.name=path.basename(pi.getMediaPath());this.start=new Time();this.start.seconds=start;this.end=new Time();this.end.seconds=start+5;}remove(){const i=this._track.clips.indexOf(this);if(i>=0)this._track.clips.splice(i,1);return 0;}}
class Track{constructor(seq,kind){this.seq=seq;this.kind=kind;this.clips=coll([]);}overwriteClip(pi,ticks){const c=new Clip(this,pi,Number(ticks)/TPS);this.clips.push(c);return true;}}
class Sequence{constructor(name){this.name=name;this.sequenceID='SEQ1';this.frameSizeHorizontal=1920;this.frameSizeVertical=1080;this.timebase=String(TPS/30);this.videoTracks=coll([new Track(this,'video')],'numTracks');this.audioTracks=coll([new Track(this,'audio')],'numTracks');this.markers={createMarker(s){return{name:'',seconds:s};}};this.playhead='END';}setPlayerPosition(v){this.playhead=String(v);return true;}exportAsMediaDirect(){throw new Error('V31 MUST NOT CALL PREMIERE EXPORT');}}
function canon(p){return path.resolve(String(p)).replace(/\//g,'\\').toLowerCase();}
function findPI(node,p){const want=canon(p),stack=[node];while(stack.length){const it=stack.pop();if(it.getMediaPath&&it.getMediaPath()&&canon(it.getMediaPath())===want)return it;for(const ch of it.children||[])stack.push(ch);}return null;}
const root=new PItem('ROOT',true);const project={rootItem:root,sequences:coll([],'numSequences'),activeSequence:null,importFiles(paths,_s,target){target=target||root;for(const p of paths)if(!findPI(root,p))target.children.push(new PItem(p,false));return true;},createNewSequenceFromClips(name,items){const s=new Sequence(name);this.sequences.push(s);this.activeSequence=s;s.videoTracks[0].overwriteClip(items[0],'0');s.audioTracks[0].overwriteClip(items[0],'0');return s;},openSequence(){return true;},deleteSequence(seq){const i=this.sequences.indexOf(seq);if(i>=0)this.sequences.splice(i,1);return true;},saveAs(p){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,Buffer.alloc(5000,2));return true;}};
global.app={project,enableQE(){global.qe=qe;return qe;}};
const qe={project:{getActiveSequence(){const s=project.activeSequence;return{addTracks(v){if(v>0)for(let i=0;i<v;i++)s.videoTracks.push(new Track(s,'video'));else s.audioTracks.push(new Track(s,'audio'));}};}}}; global.$={sleep(){}};
const files=['bootstrap.mp4','scene1.mp4','scene2.mp4','voice.wav'];for(const f of files)fs.writeFileSync(path.join(tmp,f),Buffer.alloc(f.includes('scene')?25000:5000,1));
const engineMp4=path.join(tmp,'out.mp4');fs.writeFileSync(engineMp4,Buffer.alloc(220000,3));const before=fs.statSync(engineMp4).size;
const map={schema:'HEXA_PREMIERE_EDIT_MAP_V31',version:'2.1',project:{width:1920,height:1080,fps:30},events:[],pre_rendered_motion_event_count:7,selective_text_event_count:2,assembly:{execution_mode:'PREMIERE_2022_ANIMATED_SCENE_MEDIA_ASSEMBLY',xml_import_forbidden:true,sequence_bootstrap_media:path.join(tmp,'bootstrap.mp4'),sequence_name:'HEXA_V31_MASTER',video_items:[{clip_display_name:'S1',source_path:path.join(tmp,'scene1.mp4'),start_seconds:0,end_seconds:1,premiere_track_index:0,item_role:'ANIMATED_SCENE_MEDIA',start_frame:0},{clip_display_name:'S2',source_path:path.join(tmp,'scene2.mp4'),start_seconds:1,end_seconds:2,premiere_track_index:0,item_role:'ANIMATED_SCENE_MEDIA',start_frame:30}],audio_items:[{clip_display_name:'FINAL_VOICE_OVER',source_path:path.join(tmp,'voice.wav'),start_seconds:0,end_seconds:2,premiere_track_index:0}],markers:[],required_video_tracks:1,required_audio_tracks:1,runtime_report_path:path.join(tmp,'runtime.json'),project_save_path:path.join(tmp,'out.prproj'),production_mp4_path:engineMp4,export_required:false,final_mp4_authority:'ENGINE_CONCAT_OF_IDENTICAL_ANIMATED_SCENE_MEDIA'}};
const mapPath=path.join(tmp,'map.json');fs.writeFileSync(mapPath,JSON.stringify(map));
vm.runInThisContext(fs.readFileSync(path.join(__dirname,'../extension/jsx/host.jsx'),'utf8'),{filename:'host.jsx'});
const result=$._hexaV31.assembleAndApply(mapPath);if(!String(result).startsWith('PASS:'))throw new Error(result);
const rr=JSON.parse(fs.readFileSync(map.assembly.runtime_report_path,'utf8'));
if(rr.status!=='PASS'||rr.stage!=='COMPLETE'||rr.motion_engine!=='PRE_RENDERED_ANIMATED_SCENE_MEDIA'||rr.text_engine!=='PRE_RENDERED_SELECTIVE_TYPOGRAPHY')throw new Error('runtime engine contract failed');
if(rr.engine_final_mp4_verified!==true||rr.engine_final_mp4_bytes!==before)throw new Error('engine MP4 verification failed');
if(rr.still_image_keyframe_dependency!==false||rr.transform_effect_required!==false||Number(rr.premiere_keyframes_written)!==0)throw new Error('no-keyframe contract failed');
if(rr.animated_scene_media_verified!==2||rr.video_items_placed!==2||rr.pre_rendered_motion_events_certified!==7||rr.selective_text_events_certified!==2)throw new Error('physical parity contract failed');
if(rr.timeline_readback_pass!==true||rr.video_timeline_readback_verified!==2||rr.audio_timeline_readback_verified!==1||Math.abs(Number(rr.timeline_duration_seconds)-2)>1e-6)throw new Error('timeline readback contract failed');
if(!Array.isArray(rr.video_timeline_readback)||rr.video_timeline_readback.length!==2||!Array.isArray(rr.audio_timeline_readback)||rr.audio_timeline_readback.length!==1)throw new Error('timeline readback evidence missing');
if(!fs.existsSync(map.assembly.project_save_path)||fs.statSync(map.assembly.project_save_path).size<4096)throw new Error('project physical readback missing');
if(fs.statSync(engineMp4).size!==before)throw new Error('Premiere modified engine final MP4');
if(project.activeSequence.playhead!=='0'||rr.playhead_reset_to_start!==true)throw new Error('playhead reset failed');
const badMap=JSON.parse(JSON.stringify(map));badMap.assembly.video_items[1].start_seconds=1.25;badMap.assembly.video_items[1].start_frame=38;badMap.assembly.runtime_report_path=path.join(tmp,'runtime-bad-gap.json');badMap.assembly.project_save_path=path.join(tmp,'bad-gap.prproj');
const badMapPath=path.join(tmp,'map-bad-gap.json');fs.writeFileSync(badMapPath,JSON.stringify(badMap));
const badResult=$._hexaV31.assembleAndApply(badMapPath);if(!String(badResult).startsWith('FAIL: stage=PHYSICAL_TIMELINE_QA'))throw new Error('host accepted animated-media timeline gap: '+badResult);
const badReport=JSON.parse(fs.readFileSync(badMap.assembly.runtime_report_path,'utf8'));if(badReport.status!=='FAIL'||badReport.stage!=='PHYSICAL_TIMELINE_QA'||String(badReport.error).indexOf('continuity mismatch')<0)throw new Error('timeline-gap failure evidence missing');
console.log('V31_0_1_PREMIERE_PROJECT_ONLY_HOST_MOCK_PASS');
